### ISSUE TITLE
Github content feedback

### ISSUE THREAD

**Issue by floridop** [fredholmP/MNXB01-FinalProject#7]
# Workplan
It seems you did not plan any shared coding since the very beginning.
Detail vary depending on group member tasks.

# Changelog:
Odd format, does not match the suggested ones. Impossible to know
who did what.

# README.md

The document is minimalistic. Tries to organize the content organically.

## Philip's code:
The documentation says we should use Ubuntu 20. The code should have
run on Aurora which is not Ubuntu. I do not think warning the user
that the code will not work in the target system is nice, but 
better than nothing.

How to use the code is well explained.

## Chris' code:
Good descripition of the steps the user followed. However, I have no idea
how to run Chris' code, despite the section title.

I tried to run the terrible filename "Unsaved Document 1" which tells me
nothing about what the content is and doesn't even have the standard
.C extension.

Something is drawn on screen, but I think the data sources mentioned
in the untitled file are missing and therefore nothing is drawn.

Did you test this code on Aurora? I cannot grade this.

I understand you used Excel to clean the datasets, but you
give us no real way to replicate this in an automatic manner. What you
wrote it's not even some pseudocode.

I cannot grade this part of the project.

# Code:

 - Philip's code runs on Aurora despite Ubuntu 20 not being
involved in the process.

 - Chris code runs but there are no instructions and no datasets to 
see whether it does the expected thing.

# Summary

Chris part cannot be graded until they perform the requested actions:

**ACTIONS: Chris, please provide:**
 - the cleaned datasets files on github
 - An explanation of the content of each dataset in the README.md file.
 - instructions how to run your code against these datasets.

**Comment by fredholmP** [comment]
Thank you for your feedback!

I am surprised that you got my code to run on Aurora, I did not. Did you run any special commands other than loading the Gcc-module and sourcing the root script? I had some issues that I described here [here](https://github.com/fredholmP/MNXB01-FinalProject/issues/6#issuecomment-1302354189 ) .

**Comment by fredholmP** [comment]
To clarify: I did not test running the latest version of my code on Aurora. I did however have the really strange issues (which I described in on the linked page) that went away as soon as I ran my code outside of Aurora.

**Comment by floridop** [comment]
Hi @fredholmP 
I simply initialized root by sourcing the script provided during the course. Then I accessed your root scripts folder and ran them as described in the readme. Was there more to it? I didn't even load any C++ module.

**Comment by floridop** [comment]
If you were trying to use the root that you copied from Ubuntu on Aurora, that makes no sense. Builds for different distributions expect libraries to be on different folders with different names. It cannot work. You need root for CentOS7. The linking is different in the two builds.

**Comment by floridop** [comment]
Hi @chlee295 

Thanks for the updated code, now I can see something I can test. Some comments about your submission.

* "Final Project" 
   - is a bad filename for some code as it contains spaces. Please avoiud filenames with spaces when coding professionally.
   - it has no .C extension (assuming is a Cint script) which makes it hard to understand what the content can be without looking into the file. Luclily the README.md reveals it is a ROOT script indirectly, by looking at the commands you wrote.
   - it is a simple copy paste of ROOT commands, not a real Cint script or a piece of ROOT and C++ code, which is quite disappointing given the examples provided during the course AND in the project skeleton. I do not understand what your problem is with using provided material.

The code works as explained in the README and now it is enough information to grade, this issue is closed.
